# Generated by Django 2.2 on 2021-06-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='total',
            new_name='earned',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.Employee'),
            preserve_default=False,
        ),
    ]
