# Generated by Django 2.2 on 2021-06-01 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210601_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecard',
            name='employee',
        ),
        migrations.AddField(
            model_name='timecard',
            name='employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='timecards', to='app.Employee'),
            preserve_default=False,
        ),
    ]
