# Generated by Django 2.2 on 2021-06-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210601_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='timecard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='app.TimeCard'),
        ),
        migrations.AddField(
            model_name='report',
            name='timecard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.TimeCard'),
        ),
    ]
