# Generated by Django 2.2 on 2021-06-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210601_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='rate_effective_date',
        ),
        migrations.AlterField(
            model_name='point',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=None, related_name='points', to='app.PointRate'),
        ),
    ]
