# Generated by Django 2.2 on 2021-06-02 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210601_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='points', to='app.PointRate'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='clock_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
