# Generated by Django 2.2 on 2021-06-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210602_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='submitted_to',
        ),
    ]
