# Generated by Django 2.2 on 2021-06-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_report_submitted_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
