# Generated by Django 2.2 on 2021-06-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapoint',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_points', to='app.Report'),
        ),
    ]
