# Generated by Django 2.2 on 2021-06-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210607_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrate',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_rates', to='app.Employee'),
        ),
    ]
