# Generated by Django 2.2 on 2021-08-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_pointrate_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapoint',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_points', to='app.Employee'),
        ),
    ]
