# Generated by Django 2.2 on 2021-06-09 20:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to=accounts.models.path_and_rename),
        ),
    ]
