# Generated by Django 2.2 on 2021-06-10 01:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210609_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.jpeg', upload_to=accounts.models.path_and_rename),
        ),
    ]
